spring.application.name=user-service

server.port=9300
spring.config.import=optional:configserver:http://localhost:8888

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/user_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Rishu@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#for redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#mailConfig


#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#------>
#vendor.service.url=http://localhost:8082

