server.port=7070
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

## Route 0: User / Auth / Ecommerce Service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/ecommerce/**
spring.cloud.gateway.routes[0].predicates[1]=Path=/customers/**
spring.cloud.gateway.routes[0].predicates[2]=Path=/auth/**

## Route 1: Admin / Vendor Service
spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=lb://admin-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/**

## JWT Secret
jwt.secret=EurkPtDJ5ucKo3zZ6J3mRfn85qixZo6TzKVNYOwERa4